sudo: required

env:
  global:
    - DOCKER_VERSION=1.9.1  # Install Docker version 1.9.1

services:
  - docker

script:
  - docker build -t grahovsky/postgrepro:latest .
  - docker create -it --name postgrepro grahovsky/postgrepro:latest
  - docker start postgrepro
  - docker exec -it postgrepro psql -U postgres -l
  - docker stop postgrepro
